#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TF_DIR="$PROJECT_ROOT/infra/main"

# Wait for LocalStack to be healthy before terraform tries to talk to it.
# Idempotent: returns immediately if already up. Bounded so it won't hang forever.
echo "=== Waiting for LocalStack health ==="
for _ in $(seq 1 60); do
  if curl -fs http://localhost:4566/_localstack/health >/dev/null 2>&1; then
    break
  fi
  sleep 1
done
if ! curl -fs http://localhost:4566/_localstack/health >/dev/null 2>&1; then
  echo "LocalStack did not become healthy within 60s. Is it running?" >&2
  exit 1
fi

echo "=== Provisioning LocalStack resources with Terraform ==="
cd "$TF_DIR"

# LocalStack state is ephemeral; swap the prod S3 backend for a local file
# backend via a terraform override (gitignored, only exists during dev).
cat > backend_override.tf <<'EOF'
# Auto-generated by scripts/localstack-provision.sh. Do not edit.
# Overrides the S3 backend in versions.tf with a local backend for dev.
terraform {
  backend "local" {}
}
EOF

terraform init -input=false -reconfigure
terraform apply -var-file=envs/dev.tfvars -auto-approve -input=false

echo ""
echo "=== LocalStack provisioning complete ==="
echo "S3 bucket and IAM resources are ready."
echo ""
echo "Verify with:"
echo "  awslocal s3 ls --endpoint-url http://localhost:4566"
